version: "3.3"

services:
  project_name:
    build: .
    container_name: project_name
    depends_on:
      - postgres_db
    entrypoint: [ 'python', 'main.py' ]
    env_file:
      - .env
    ports:
      - port:port

  postgres_db:
    image: postgres
    container_name: db_name
    env_file: .env
    ports:
      - "5432:5432"
